### ISSUE TITLE
VMWare Horizon 4.3 does not work

### ISSUE THREAD

**Issue by frakman1** [Gibbio/RPiTC_Builder#6] opened 2017-03-02 18:30 UTC
Using RPi3 with latest release of RPiTC v3 1.12.

As many users have mentioned in the [forum](http://forum.armtc.net/), VMWare Horizon 4.3 does not work. After connecting to the remote desktop, it would briefly flash the desktop and then disconnect immediately. Sometimes only a black screen is observed before disconnecting.

It seems that VMWare Horizon 3.5 is needed. I am unable to find it anywhere in the RPiTC Builder nor on your [website](http://rpitc.blogspot.com/). I tried to flash an older release from [here](http://downloads.mysyapps.com/raspberrypi/rpitc/). Neither `RPiTC-2_r1.1.img.zip` nor `RPiTC2_r1.4.img.zip` worked on my RPi3 nor my RPi-zero (wouldn't even boot)

**Can you please provide instructions on how to downgrade VMWare Horizon (4.3->3.5) or how to install it directly from within the RPiTC v3 1.12 release as it is the only image that I can currently run on my R.Pi3.**

Thank you
P.S. I had to manually install `gparted` and resize my partition before I could successfully run `bashme.sh` without running out of space. This seems like something that should either be taken care of by the script, or have instructions provided to the user to do so.

**Comment by frakman1** [comment] 2017-03-03 01:49
I confirmed that the last working version of RPiTC was v3 1.11 on the R.Pi 3
Something must have broken VMWare Horizon in 4.3/ v3 1.12

**Comment by frakman1** [comment] 2017-03-03 02:11
Upon loading the v3 1.11 image, I am unable to install the VMWare Horizon client at all. I run into this error 
(screenshot because I can't copy and paste in that terminal)
![image](https://cloud.githubusercontent.com/assets/5826484/23535446/63f07d46-ff8c-11e6-9cbe-7125948f6f97.png)

**Comment by Gibbio** [comment] 2017-03-17 10:26
I'll close this issue as duplicate of #7

**Closed by Gibbio** 2017-03-17 10:26 UTC
